spring.application.name=finance-api

# PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Seed data
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}